server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: resume-staticdata-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resume_staticdata}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}
  cache:
    type: simple
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration/staticdata_nodup
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

app:
  cors:
    allowed-origins:
      - ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}
